"""
Merge section outputs into a single Deep-Read report (Markdown).
"""

from __future__ import annotations

from typing import List

from orchestration.deep_read.section_agents import SectionResult


def merge_report(
    sections: List[SectionResult],
    title: str,
    source: str,
) -> str:
    lines = [
        f"# Deep-Read Report: {title}",
        "",
        f"**Source:** {source}",
        "",
        "---",
        "",
        "> This report follows how researchers read a paper: metadata → problem → method → "
        "figures/tables → results → limitations. Written for first-time readers.",
        "",
    ]
    for sec in sections:
        lines.append(f"## {sec.title}")
        lines.append("")
        lines.append(sec.content)
        lines.append("")
        lines.append("---")
        lines.append("")

    lines.append("*Generated by Deep-Read pipeline*")
    return "\n".join(lines)
